from datetime import datetime
from sqlalchemy import Index
from SnapVault import db


class Document(db.Model):
    # Database table name.
    __tablename__ = 'document'

    # -------------------- Primary Key --------------------

    # Unique ID for each document.
    id = db.Column(db.Integer, primary_key=True)

    # -------------------- Owner --------------------

    # Foreign key to the User table.
    # Each Document belongs to exactly one User.
    # If the User is deleted, all their Documents are also deleted.
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        nullable=False,
    )

    # -------------------- File Information --------------------

    # Original filename uploaded by the user.
    # Used only for display purposes.
    original_filename = db.Column(db.String(255), nullable=False)

    # Unique filename generated by the application (UUID).
    # Used to store the file safely on disk.
    stored_filename = db.Column(db.String(255), unique=True, nullable=False)

    # Size of the uploaded file (in bytes).
    file_size = db.Column(db.Integer, nullable=False)

    # SHA-256 hash of the file.
    # Used to detect duplicate uploads.
    file_hash = db.Column(db.String(64), nullable=False)

    # Relative path of the file inside the uploads folder.
    file_path = db.Column(db.String(500), nullable=False)

    # -------------------- OCR --------------------

    # Text extracted from the image using EasyOCR.
    # NULL if OCR has not run or has failed.
    ocr_text = db.Column(db.Text, nullable=True)

    # OCR status.
    #
    # pending -> OCR has not run yet.
    # success -> OCR completed successfully.
    # failed  -> OCR failed.
    ocr_status = db.Column(
        db.String(20),
        nullable=False,
        default='pending',
    )

    # -------------------- Classification --------------------

    # Category predicted for the document.
    # Default category is Miscellaneous.
    category = db.Column(
        db.String(50),
        nullable=False,
        default='Miscellaneous',
    )

    # -------------------- Timestamp --------------------

    # Time when the document was uploaded.
    uploaded_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
    )

    # -------------------- Relationships --------------------

    # One Document can have many Reminders.
    #
    # Access:
    # document.reminders
    # reminder.linked_document
    #
    # passive_deletes=True
    # If a Document is deleted, let the database handle the
    # Reminder foreign key instead of SQLAlchemy.
    reminders = db.relationship(
        'Reminder',
        backref='linked_document',
        lazy=True,
        passive_deletes=True,
    )

    # -------------------- Debugging --------------------

    # String representation of a Document object.
    # Used only for debugging and logging.
    def __repr__(self) -> str:
        return (
            f'<Document id={self.id} '
            f'category={self.category!r} '
            f'ocr_status={self.ocr_status!r}>'
        )


# -------------------- Database Index --------------------

# Composite index on (user_id, category).
#
# Makes queries like:
#
# SELECT * FROM document
# WHERE user_id = ?
# AND category = ?
#
# much faster, especially for dashboard statistics.
Index('ix_document_user_category', Document.user_id, Document.category)